### ISSUE TITLE
wabbit pause?

### ISSUE THREAD

**Issue by onelesd** [pma/wabbit#12]
Is there a way to pause consumers?

I tried doing a AMQP.Basic.cancel (with the intention of AMQP.Basic.consume to resume) and received an :unexpected_delivery_and_no_default_consumer error.

**Comment by pma** [comment]
@onelesd Taking the example (https://github.com/pma/wabbit/blob/master/examples/direct_exchange.ex) as reference, I think that if you implement a Consumer that manually controls demand, you can suspend by not asking for more messages. If the Consumer stops asking for more messages, the Source will stop taking more messages from the queue once the prefetch_count limit is hit.

You can look at one implementation example in GenStage to see how to manually handle demand: https://github.com/elixir-lang/gen_stage/blob/master/examples/rate_limiter.exs.

The Wabbit lib does not currently implement any facility to suspend at the queue consumer stage. I think this should be done using the GenStage API only, not exposing any of the RabbitMQ details.

Also note that Wabbit uses the Erlang client directly, so instead of the functions from the amqp Elixir client (AMQP.Basic) you should consider those in Wabbit.Basic. One takes the channel as a struct and the other takes the channel directly as the channel pid from the Erlang client.

**Comment by onelesd** [comment]
We ended up using the GenStage API as in the 2nd example.

Thank you for your help!
